apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluentd-read
  labels:
    app: {{ template "fluentd.fullname" . }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-read
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: {{ .Release.Namespace }}
